### ISSUE TITLE
Sample using Oauth

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/python-analytics-admin#232]
Currently the only sample I can find [Quickstart](https://github.com/googleapis/python-analytics-admin/blob/main/samples/quickstart.py) uses service accounts.

Please include a sample for bot web applications and installed application credentials.   We need a way of requesting permission from a user and not using a preauthorized service account.

**Comment by ikuleshov** [comment]
Linda, here is what we have for the Data API. Is this something you were looking for?

https://github.com/googleapis/python-analytics-data/blob/main/samples/snippets/quickstart_oauth2.py
https://github.com/googleapis/python-analytics-data/blob/main/samples/snippets/quickstart_json_credentials.py

**Comment by RickyAccel** [comment]
Hi I am looking for the same. The Data API examples provided look to still require a service account. I would like to authorize as my user.  Something like below, but it gives me an insufficient scopes error. 


```
from google.analytics.admin  import AnalyticsAdminServiceClient 
import google.auth
def list_accounts(credentials):
    """Lists the available Google Analytics accounts."""
    from google.analytics.admin import AnalyticsAdminServiceClient

    client = AnalyticsAdminServiceClient(credentials=credentials)

    # Displays the configuration information for all Google Analytics accounts
    # available to the authenticated user.
    for account in client.list_accounts():
        print(account)

credentials, project = google.auth.default(scopes=['https://www.googleapis.com/auth/analytics.readonly','https://www.googleapis.com/auth/analytics.edit'])

list_accounts(credentials)
```

**Comment by ikuleshov** [comment]
> Hi I am looking for the same. The Data API examples provided look to still require a service account. I would like to authorize as my user. Something like below, but it gives me an insufficient scopes error.
> 
> ```
> import google.auth
> def list_accounts(credentials):
>     """Lists the available Google Analytics accounts."""
>     from google.analytics.admin import AnalyticsAdminServiceClient
> 
>     client = AnalyticsAdminServiceClient(credentials=credentials)
> 
>     # Displays the configuration information for all Google Analytics accounts
>     # available to the authenticated user.
>     for account in client.list_accounts():
>         print(account)
> 
> credentials, project = google.auth.default(scopes=['https://www.googleapis.com/auth/analytics.readonly','https://www.googleapis.com/auth/analytics.edit'])
> 
> list_accounts(credentials)
> ```

The [quickstart_oauth2.py](https://github.com/googleapis/python-analytics-data/blob/main/samples/snippets/quickstart_oauth2.py) sample does not use service account credentials. Just to debug the issue, can you try following the [API Quickstart using the command line](https://developers.google.com/analytics/devguides/config/admin/v1/quickstart-cli) and see if you can make the call using OAuth2 without a client library.

**Comment by RickyAccel** [comment]
I got it! You rock @ikuleshov ! I'll list what I did here for anyone else that faces my same issue. You can start at step 2.

1. Followed the command line instructions [API Quickstart using the command line](https://developers.google.com/analytics/devguides/config/admin/v1/quickstart-cli) 
2. Needed to run ```unset GOOGLE_APPLICATION_CREDENTIALS```
3. Ran the Authentication step again (step 1) and received the error ``` ERROR: (gcloud.auth.application-default.login) Only client IDs of type 'installed' are allowed, but encountered type 'web'```
4. Went to the API & Services Credentials in GCP and created credentials for Desktop App
5. Downloaded the credentials and ran the authenticate step with the new desktop credentials
6. I was able to authenticate from CLI
7. Ran my Python code and success from there too!

**Comment by hnandiwada** [comment]
Is there a way to authenticate with just a client ID, client secret, and access token (eg without browser or CLI)? Using the `google-api-python-client` we were able to do the following:
```
        token_uri = "https://oauth2.googleapis.com/token"
        credentials = google.oauth2.credentials.Credentials(
            token=access_token,
            token_uri=token_uri,
            client_id="client_id",
            client_secret=["client_secret"],
        )
        authorized = AuthorizedHttp(credentials=credentials)
        service = build("analytics", "v3", http=authorized)
```
and using the ads client we were able to do this
```
    config_dict = {
        "developer_token": "developer_token",
        "client_id": "client_id",
        "client_secret": "client_secret",
        "refresh_token": "refresh_token",
        "version": "v10",
        "use_proto_plus": True,
    }
    googleads_client = GoogleAdsClient.load_from_dict(config_dict)
```
Is there an equivalent for this API? 
(https://github.com/googleapis/python-analytics-data/issues/244)

**Comment by LindaLawton** [comment]
It would be nice if there was a way to feed it the credetinals.json file or a path to it and it would just load it.

**Comment by hnandiwada** [comment]
Solved! We actually were able to pass in the Credentials object like so
```
        token_uri = "https://oauth2.googleapis.com/token"
        credentials = google.oauth2.credentials.Credentials(
            token=access_token,
            token_uri=token_uri,
            client_id=client_id,
            client_secret=["client_secret"],
        )
       service = AnalyticsAdminServiceClient(credentials=credentials)
```

**Comment by parthea** [comment]
I'm going to close this issue as the issue was resolved.
