### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/python-analytics-admin#342]
Trying to understand how to set page size for an account summaries list.    

    # Using a default constructor instructs the client to use the credentials
    # specified in GOOGLE_APPLICATION_CREDENTIALS environment variable.
    client = AnalyticsAdminServiceClient(credentials=credentials)

    # Make the request
    results = client.list_account_summaries(page_size = 1)

    # Displays the configuration information for all Google Analytics accounts
    # available to the authenticated user.
    print("Result:")
    for account in results:
        print(account)

It doesn't seem to exist except in the alpha and beta versions.

>TypeError: list_account_summaries() got an unexpected keyword argument 'page_size'

**Comment by suztomo** [comment]
@LindaLawton Sorry for late response. `page_size` is a parameter of `ListAccountSummariesRequest`. https://googleapis.dev/python/analyticsadmin/latest/admin_v1beta/types.html#google.analytics.admin_v1beta.types.ListAccountSummariesRequest
